server:
  port: 8080
  servlet:
    context-path: /farming


#logging:
#  pattern:
#    console: "%d - [%thread] - %msg%n"
#  level:
#    web: info, error, debug
#    com.crowdfunding.farming: error, info, debug

spring:
  application:
    name: farming
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: Kevin614718
#    jedis:
#      pool:
#        max-active: 100
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#    timeout: 5000ms
#    cache:
#      type: redis

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1   # 设置最大的请求文件的大小

  datasource:
    #url: jdbc:mysql://localhost:3306/nongye?serverTimezone=UTC
    url: jdbc:mysql://47.98.216.68/crowd-funding?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    #password: Kevin614718
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.crowdfunding.farming.ptojo
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql

farming:
  jwt:
    secret: farming@Login(Auth}*^31)&zlj% # 登录校验的密钥
    #pubKeyPath: F:/upload/rsa/rsa.pub ＃公钥地址
    #priKeyPath: F:/upload/rsa/rsa.pri
    pubKeyPath: /home/rsa/rsa.pub # 公钥地址
    priKeyPath: /home/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieMaxAge: 1800 #cookie的过期时间
    cookieName: FARMING_TOKEN #cookie的名称